import {lessons} from './week3-content.mjs';
import {slideText} from './week3-slides.mjs';
import {isCorrect} from './network-math.mjs';
import {cliqueNodes,cliqueEdges,coreNodes,coreEdges,cliqueType,peelLayer} from './week3-math.mjs';
const q=s=>document.querySelector(s),esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
let state={visited:[],reflections:{}};try{const data=JSON.parse(localStorage.getItem('ge2234-week3')||'null');if(data&&Array.isArray(data.visited)&&data.reflections)state=data;}catch{}
function save(){try{localStorage.setItem('ge2234-week3',JSON.stringify(state));}catch{}}
function progress(){const percent=Math.round(100*lessons.filter(l=>state.visited.includes(l.id)).length/lessons.length);q('#progressText').textContent=percent+'%';q('#progressBar').style.width=percent+'%';}
function slideViewer(start,end){return `<details class="original-slides" data-start="${start}" data-end="${end}"><summary>Original lecture slides ${start}–${end}</summary><div class="slide-controls"><button class="ghost slide-prev">← Previous slide</button><label>Slide <select>${Array.from({length:end-start+1},(_,i)=>`<option>${start+i}</option>`).join('')}</select></label><button class="ghost slide-next">Next slide →</button></div><figure><img loading="lazy" alt="Original lecture slide ${start}" src="w3-slides/slide-${String(start).padStart(2,'0')}.jpg"><figcaption>Original slide <span class="slide-number">${start}</span> of 64</figcaption></figure><details><summary>Slide text</summary><pre class="slide-text">${esc(slideText[start-1])}</pre></details></details>`;}
q('#lessonBody').innerHTML=lessons.map((l,i)=>`<section class="chapter${i===0?' active':''}" id="${l.id}"><div class="kicker">LECTURE 03 · ${String(i+1).padStart(2,'0')} / ${lessons.length}</div>${l.body}${slideViewer(...l.slides)}<div class="pager">${i?`<button class="ghost" data-section="${lessons[i-1].id}">← Back</button>`:'<a class="ghost" href="/Ge2234/week2/">← Week 2</a>'}${i<lessons.length-1?`<button class="primary" data-section="${lessons[i+1].id}">Continue →</button>`:'<button class="ghost" data-section="overview">Return to overview</button>'}</div></section>`).join('');
q('#chapterSelect').innerHTML=lessons.map((l,i)=>`<option value="${l.id}">${i+1}. ${l.title}</option>`).join('');
function show(id){if(!lessons.some(l=>l.id===id))id='overview';document.querySelectorAll('.chapter').forEach(s=>s.classList.toggle('active',s.id===id));q('#chapterSelect').value=id;history.replaceState(null,'','#'+id);if(!state.visited.includes(id))state.visited.push(id);save();progress();q('#sidebar').classList.remove('open');window.scrollTo(0,0);}
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>show(b.dataset.section));q('#chapterSelect').onchange=e=>show(e.target.value);q('#menu').onclick=()=>q('#sidebar').classList.toggle('open');window.addEventListener('hashchange',()=>show(location.hash.slice(1)));
document.querySelectorAll('.original-slides').forEach(box=>{const select=box.querySelector('select');function update(){const n=+select.value;box.querySelector('img').src=`w3-slides/slide-${String(n).padStart(2,'0')}.jpg`;box.querySelector('img').alt=`Original lecture slide ${n}: ${slideText[n-1].split('\n').filter(Boolean)[0]||'Network illustration'}`;box.querySelector('.slide-number').textContent=n;box.querySelector('.slide-text').textContent=slideText[n-1];box.querySelector('.slide-prev').disabled=n===+box.dataset.start;box.querySelector('.slide-next').disabled=n===+box.dataset.end;}select.onchange=update;box.querySelector('.slide-prev').onclick=()=>{select.value=+select.value-1;update();};box.querySelector('.slide-next').onclick=()=>{select.value=+select.value+1;update();};update();});
document.querySelectorAll('.w3-quiz').forEach(box=>box.querySelectorAll('button').forEach(b=>b.onclick=()=>{box.querySelectorAll('button').forEach(x=>x.className='');const ok=b.dataset.choice===box.dataset.answer;b.className=ok?'ok':'no';const feedback=box.querySelector('.feedback');feedback.className='feedback '+(ok?'good':'bad');feedback.textContent=(ok?'Correct. ':'Try again. ')+box.querySelector('template').content.textContent;}));
document.querySelectorAll('.w3-calc').forEach(box=>{const inputs=[...box.querySelectorAll('input')];box.querySelector('.check').onclick=()=>{let count=0;inputs.forEach(x=>{const ok=isCorrect(x.value,+x.dataset.answer);x.className=ok?'correct':'wrong';x.setAttribute('aria-invalid',String(!ok));if(ok)count++;});const f=box.querySelector('.feedback');f.className='feedback '+(count===inputs.length?'good':'bad');f.textContent=count===inputs.length?'All calculations are correct.':`${count} of ${inputs.length} correct. Review the highlighted fields or open the worked solution.`;};box.querySelector('.reset').onclick=()=>{inputs.forEach(x=>{x.value='';x.className='';x.removeAttribute('aria-invalid');});box.querySelector('.feedback').textContent='';};});
document.querySelectorAll('[data-reflection]').forEach(t=>{t.value=state.reflections[t.id]||'';t.oninput=()=>{state.reflections[t.id]=t.value;save();};});q('#completeW3').onclick=()=>{state.visited=lessons.map(l=>l.id);save();progress();q('#completeStatus').textContent='Week 3 marked complete. You can revisit any section.';};
const pos={'1':[65,140],'2':[190,225],'3':[315,160],'4':[190,45],'5':[440,70],'6':[525,140],'7':[605,215]};
function graph(nodes,edges,positions,active=nodes,chosen=[]){return `<svg class="teaching-network" viewBox="0 0 670 270" role="img" aria-label="Network with edges ${edges.map(x=>x.join('–')).join(', ')}">${edges.map(([a,b])=>`<line x1="${positions[a][0]}" y1="${positions[a][1]}" x2="${positions[b][0]}" y2="${positions[b][1]}" stroke="${active.includes(a)&&active.includes(b)?'#e79a41':'#dce3e9'}" stroke-width="4"/>`).join('')}${nodes.map(n=>`<circle cx="${positions[n][0]}" cy="${positions[n][1]}" r="23" fill="${chosen.includes(n)?'#43bdd6':active.includes(n)?'white':'#e8edf2'}" stroke="${active.includes(n)?'#086bb6':'#b4bdc8'}" stroke-width="3"/><text x="${positions[n][0]}" y="${positions[n][1]+6}" text-anchor="middle" font-size="18">${n}</text>`).join('')}</svg>`;}
let chosen=[];function cliqueDraw(){q('#cliqueGraph').innerHTML=graph(cliqueNodes,cliqueEdges,pos,cliqueNodes,chosen);q('#cliquePicker').innerHTML=cliqueNodes.map(n=>`<button aria-pressed="${chosen.includes(n)}" data-node="${n}">${n}</button>`).join('');q('#cliquePicker').querySelectorAll('button').forEach(b=>b.onclick=()=>{chosen=chosen.includes(b.dataset.node)?chosen.filter(n=>n!==b.dataset.node):[...chosen,b.dataset.node];cliqueDraw();q('#cliqueFeedback').textContent='';});}cliqueDraw();q('#checkClique').onclick=()=>{const result=cliqueType(chosen);q('#cliqueFeedback').textContent={small:'Select at least two nodes.',incomplete:'Not a clique: at least one pair has no direct tie.',extendable:'This is complete but not maximal: another node can be added.',maximal:`Correct: {${chosen.slice().sort().join(', ')}} is a maximal clique.`}[result];};
let active=[...coreNodes],round=0;function coreDraw(message=''){q('#coreGraph').innerHTML=graph(coreNodes,coreEdges,pos,active);const layer=peelLayer(active,+q('#coreK').value);q('#coreStatus').textContent=message||`Round ${round}: active nodes {${active.join(', ')||'none'}}. ${layer.length?'Press the button to remove the next low-degree layer.':`Stable ${q('#coreK').value}-core reached.`}`;q('#peel').disabled=layer.length===0;}function resetCore(){active=[...coreNodes];round=0;coreDraw();}q('#coreK').onchange=resetCore;q('#resetCore').onclick=resetCore;q('#peel').onclick=()=>{const layer=peelLayer(active,+q('#coreK').value);active=active.filter(n=>!layer.includes(n));round++;coreDraw(`Round ${round}: removed {${layer.join(', ')}}. Remaining: {${active.join(', ')||'none'}}.${peelLayer(active,+q('#coreK').value).length?' Recalculate degrees before the next round.':' Stable core reached.'}`);};coreDraw();
const bn=['A','B','C','D','E','F'],be=[['A','B'],['A','C'],['B','C'],['C','D'],['D','E'],['D','F'],['E','F']],bp={A:[65,45],B:[65,225],C:[235,135],D:[435,135],E:[605,45],F:[605,225]};function bridgeDraw(removed=false){q('#bridgeGraph').innerHTML=graph(bn,removed?be.filter(e=>e.join('')!=='CD'):be,bp);q('#bridgeStatus').textContent=removed?'Removed C–D. Components: {A,B,C} and {D,E,F}.':'One connected component. C–D has raw edge betweenness 9.';q('#removeBridge').disabled=removed;}q('#removeBridge').onclick=()=>bridgeDraw(true);q('#resetBridge').onclick=()=>bridgeDraw();bridgeDraw();
show(location.hash.slice(1));
